### ISSUE TITLE
The demo is not complete

### ISSUE THREAD

**Issue by Den-dp** [thinktecture/blog-configure-lazy-modules-demo#1]
According to https://www.thinktecture.com/en/angular/configuring-lazy-loaded-angular-modules/ this demo repo is not complete

Would be helpful to see it updated

**Comment by npx** [comment]
Hi @Den-dp thank you for making me aware, indeed the code was not pushed. Please check it out now!

**Comment by Den-dp** [comment]
Thanks for that!
